# Generated by Django 2.0.7 on 2022-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate_of_day',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estimate_of_day',
            name='estimate',
            field=models.IntegerField(),
        ),
    ]
